server:
  port: 8080
spring:
  application:
    name: dubbo-consumer

dubbo:
  application:
    id: dubbo-consumer-name
    name: dubbo-consumer-name
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181
